### ISSUE TITLE
Unhandled exception for location searches

### ISSUE THREAD

**Issue by dangrmous** [dangrmous/gopdx#4]
1. Do a location search with "gopdx -l "500 SW Washington, Portland"

Result: Ugly error below - need better error handling

 events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at Socket.socketOnEnd [as onend](http.js:1572:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by dangrmous** [comment]
Fixed in 0.1.16
